[tool.poetry]
name = "onboarding-template"
version = "0.1.0"
description = ""
authors = ["Zak <zsalifu@stu.ucc.edu.gh>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
