"""Add login check

Revision ID: 2def41b933cb
Revises: 9e502381e8d7
Create Date: 2024-12-17 00:36:08.792374

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2def41b933cb"
down_revision: Union[str, None] = "9e502381e8d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_refresh_tokens_user_id_users", "refresh_tokens", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_refresh_tokens_user_id_users"),
        "refresh_tokens",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column("users", sa.Column("is_logged_in", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_logged_in")
    op.drop_constraint(
        op.f("fk_refresh_tokens_user_id_users"), "refresh_tokens", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_refresh_tokens_user_id_users",
        "refresh_tokens",
        "users",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
