"""Add login check

Revision ID: 3f547318cab0
Revises: e8df03cb4e3d
Create Date: 2024-12-17 10:38:05.754816

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3f547318cab0"
down_revision: Union[str, None] = "e8df03cb4e3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "id_documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("date_of_issue", sa.Date(), nullable=False),
        sa.Column("date_of_expiry", sa.Date(), nullable=False),
        sa.Column("document_number", sa.String(length=100), nullable=False),
        sa.Column("id_number", sa.String(length=100), nullable=True),
        sa.Column("nationality", sa.String(length=100), nullable=True),
        sa.Column("gender", sa.Enum("MALE", "FEMALE", name="gender"), nullable=False),
        sa.Column(
            "document_type",
            sa.Enum("PASSPORT", "NATIONAL_ID", "DRIVER_LICENSE", name="documenttype"),
            nullable=False,
        ),
        sa.Column("url", sa.String(length=255), nullable=False),
        sa.Column("street", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=100), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_id_documents_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_id_documents")),
        sa.UniqueConstraint(
            "document_number", name=op.f("uq_id_documents_document_number")
        ),
        sa.UniqueConstraint("id_number", name=op.f("uq_id_documents_id_number")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("id_documents")
    # ### end Alembic commands ###
