"""Initial mig

Revision ID: 549fe756fd79
Revises: 
Create Date: 2024-12-13 09:54:00.859017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '549fe756fd79'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=6), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=False),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('id_card_number', sa.String(length=50), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=False),
    sa.Column('id_card_type', sa.String(length=50), nullable=False),
    sa.Column('id_card_issue_date', sa.Date(), nullable=False),
    sa.Column('id_card_expiry_date', sa.Date(), nullable=False),
    sa.Column('where_born', sa.String(length=100), nullable=True),
    sa.Column('birth_certificate_margin', sa.String(length=50), nullable=False),
    sa.Column('father_name', sa.String(length=50), nullable=True),
    sa.Column('father_occupation', sa.String(length=50), nullable=True),
    sa.Column('mother_name', sa.String(length=50), nullable=True),
    sa.Column('mother_occupation', sa.String(length=50), nullable=True),
    sa.Column('birth_certificate_issue_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('birth_certificate_margin'),
    sa.UniqueConstraint('document_number'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_card_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    # ### end Alembic commands ###
